#!/usr/bin/env bash
# ------------------------------------------------------------------
# Scarica in locale tutte le foto usate nel portfolio e nelle demo,
# cosi' il sito non dipende piu' da URL esterni (Pexels).
#
# Come si usa:
#   1. Apri il terminale nella cartella 'portfolio' (questa cartella)
#   2. Esegui:  bash download-immagini.sh
#   3. Aspetta che finisca (scarica 30 immagini, pochi secondi)
#
# Richiede 'curl', gia' presente su Mac e Linux. Su Windows puoi
# usare Git Bash (incluso in Git for Windows) o WSL.
#
# Finche' non esegui questo script il sito funziona comunque:
# le immagini vengono caricate automaticamente da Pexels come
# fallback. Dopo averlo eseguito, verranno usate le copie locali.
# ------------------------------------------------------------------
set -e
echo "Scarico 30 immagini..."

mkdir -p "images/projects"
curl -sL "https://images.pexels.com/photos/34803985/pexels-photo-34803985.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "images/projects/portfolio-personale.jpg"
echo "  ok: images/projects/portfolio-personale.jpg"
mkdir -p "images/projects"
curl -sL "https://images.pexels.com/photos/29224211/pexels-photo-29224211.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "images/projects/palestra.jpg"
echo "  ok: images/projects/palestra.jpg"
mkdir -p "images/projects"
curl -sL "https://images.pexels.com/photos/34686219/pexels-photo-34686219.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "images/projects/ristorante.jpg"
echo "  ok: images/projects/ristorante.jpg"
mkdir -p "images/projects"
curl -sL "https://images.pexels.com/photos/3998397/pexels-photo-3998397.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "images/projects/barbiere.jpg"
echo "  ok: images/projects/barbiere.jpg"
mkdir -p "demo-palestra/images"
curl -sL "https://images.pexels.com/photos/29639963/pexels-photo-29639963.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-palestra/images/hero.jpg"
echo "  ok: demo-palestra/images/hero.jpg"
mkdir -p "demo-palestra/images"
curl -sL "https://images.pexels.com/photos/29392546/pexels-photo-29392546.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-palestra/images/gallery-1.jpg"
echo "  ok: demo-palestra/images/gallery-1.jpg"
mkdir -p "demo-palestra/images"
curl -sL "https://images.pexels.com/photos/29526372/pexels-photo-29526372.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-palestra/images/gallery-2.jpg"
echo "  ok: demo-palestra/images/gallery-2.jpg"
mkdir -p "demo-palestra/images"
curl -sL "https://images.pexels.com/photos/29392549/pexels-photo-29392549.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-palestra/images/gallery-3.jpg"
echo "  ok: demo-palestra/images/gallery-3.jpg"
mkdir -p "demo-palestra/images"
curl -sL "https://images.pexels.com/photos/7031705/pexels-photo-7031705.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-palestra/images/gallery-4.jpg"
echo "  ok: demo-palestra/images/gallery-4.jpg"
mkdir -p "demo-palestra/images"
curl -sL "https://images.pexels.com/photos/13863730/pexels-photo-13863730.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-palestra/images/gallery-5.jpg"
echo "  ok: demo-palestra/images/gallery-5.jpg"
mkdir -p "demo-palestra/images"
curl -sL "https://images.pexels.com/photos/29850902/pexels-photo-29850902.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-palestra/images/gallery-6.jpg"
echo "  ok: demo-palestra/images/gallery-6.jpg"
mkdir -p "demo-ristorante/images"
curl -sL "https://images.pexels.com/photos/34686219/pexels-photo-34686219.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-ristorante/images/hero.jpg"
echo "  ok: demo-ristorante/images/hero.jpg"
mkdir -p "demo-ristorante/images"
curl -sL "https://images.pexels.com/photos/29887388/pexels-photo-29887388.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-ristorante/images/gallery-1.jpg"
echo "  ok: demo-ristorante/images/gallery-1.jpg"
mkdir -p "demo-ristorante/images"
curl -sL "https://images.pexels.com/photos/33097104/pexels-photo-33097104.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-ristorante/images/gallery-2.jpg"
echo "  ok: demo-ristorante/images/gallery-2.jpg"
mkdir -p "demo-ristorante/images"
curl -sL "https://images.pexels.com/photos/17804210/pexels-photo-17804210.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-ristorante/images/gallery-3.jpg"
echo "  ok: demo-ristorante/images/gallery-3.jpg"
mkdir -p "demo-ristorante/images"
curl -sL "https://images.pexels.com/photos/38896844/pexels-photo-38896844.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-ristorante/images/gallery-4.jpg"
echo "  ok: demo-ristorante/images/gallery-4.jpg"
mkdir -p "demo-ristorante/images"
curl -sL "https://images.pexels.com/photos/33097108/pexels-photo-33097108.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-ristorante/images/gallery-5.jpg"
echo "  ok: demo-ristorante/images/gallery-5.jpg"
mkdir -p "demo-ristorante/images"
curl -sL "https://images.pexels.com/photos/9544251/pexels-photo-9544251.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-ristorante/images/gallery-6.jpg"
echo "  ok: demo-ristorante/images/gallery-6.jpg"
mkdir -p "demo-ristorante/images"
curl -sL "https://images.pexels.com/photos/17804216/pexels-photo-17804216.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-ristorante/images/gallery-7.jpg"
echo "  ok: demo-ristorante/images/gallery-7.jpg"
mkdir -p "demo-ristorante/images"
curl -sL "https://images.pexels.com/photos/24869086/pexels-photo-24869086.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-ristorante/images/gallery-8.jpg"
echo "  ok: demo-ristorante/images/gallery-8.jpg"
mkdir -p "demo-ristorante/images"
curl -sL "https://images.pexels.com/photos/16551434/pexels-photo-16551434.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-ristorante/images/gallery-9.jpg"
echo "  ok: demo-ristorante/images/gallery-9.jpg"
mkdir -p "demo-barbiere/images"
curl -sL "https://images.pexels.com/photos/3998414/pexels-photo-3998414.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-barbiere/images/hero.jpg"
echo "  ok: demo-barbiere/images/hero.jpg"
mkdir -p "demo-barbiere/images"
curl -sL "https://images.pexels.com/photos/3998408/pexels-photo-3998408.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-barbiere/images/gallery-1.jpg"
echo "  ok: demo-barbiere/images/gallery-1.jpg"
mkdir -p "demo-barbiere/images"
curl -sL "https://images.pexels.com/photos/1805600/pexels-photo-1805600.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-barbiere/images/gallery-2.jpg"
echo "  ok: demo-barbiere/images/gallery-2.jpg"
mkdir -p "demo-barbiere/images"
curl -sL "https://images.pexels.com/photos/5853394/pexels-photo-5853394.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-barbiere/images/gallery-3.jpg"
echo "  ok: demo-barbiere/images/gallery-3.jpg"
mkdir -p "demo-barbiere/images"
curl -sL "https://images.pexels.com/photos/4625629/pexels-photo-4625629.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-barbiere/images/gallery-4.jpg"
echo "  ok: demo-barbiere/images/gallery-4.jpg"
mkdir -p "demo-barbiere/images"
curl -sL "https://images.pexels.com/photos/7518732/pexels-photo-7518732.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-barbiere/images/gallery-5.jpg"
echo "  ok: demo-barbiere/images/gallery-5.jpg"
mkdir -p "demo-barbiere/images"
curl -sL "https://images.pexels.com/photos/1570807/pexels-photo-1570807.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-barbiere/images/gallery-6.jpg"
echo "  ok: demo-barbiere/images/gallery-6.jpg"
mkdir -p "demo-barbiere/images"
curl -sL "https://images.pexels.com/photos/7697230/pexels-photo-7697230.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-barbiere/images/gallery-7.jpg"
echo "  ok: demo-barbiere/images/gallery-7.jpg"
mkdir -p "demo-barbiere/images"
curl -sL "https://images.pexels.com/photos/7697285/pexels-photo-7697285.jpeg?auto=compress&cs=tinysrgb&w=1600" -o "demo-barbiere/images/gallery-8.jpg"
echo "  ok: demo-barbiere/images/gallery-8.jpg"
echo "Fatto! Tutte le immagini sono ora salvate in locale."
